instructions = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""

lines = list(instructions.split())
splits = 0
beams = set([lines[0].index("S")])
for line in lines[1:]:
    new_beams = set()
    for beam in beams:
        if line[beam] == "^":
            new_beams.add(beam - 1)
            new_beams.add(beam + 1)
            splits += 1
        else:
            new_beams.add(beam)
    beams = new_beams
print(splits)
