from collections import defaultdict
instructions = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""

lines = list(instructions.split())
beams = {lines[0].index("S"): 1}
for line in lines[1:]:
    new_beams = defaultdict(lambda: 0)
    for beam, timelines in beams.items():
        if line[beam] == "^":
            new_beams[beam - 1] += timelines
            new_beams[beam + 1] += timelines
        else:
            new_beams[beam] += timelines
    beams = new_beams
print(sum(beams.values()))
